baseURL: https://crestfallenlarp.com
title: Crestfallen
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true
ui.sidebar_menu_compact: true
ui.sidebar_menu_foldable:  true
taxonomies:
  tag: tags
  category: categories
params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
  copyright: Beren Olean
  version_menu: Releases
  archived_version: false
  version: '0.0'
  # url_latest_version: 'https://example.com'
  # github_repo: 'https://github.com/sjbennett123/crestfallen'
  # github_project_repo: 'https://github.com/google/docsy'
  # github_branch: master
  # gcs_engine_id: d72aa9b2712488cc3
  algolia_docsearch: false
  offlineSearch: true
  prism_syntax_highlighting: false
  ui:
    breadcrumb_disable: false
    footer_about_disable: true
    navbar_logo: true
    navbar_translucent_over_cover_disable: false
    sidebar_menu_compact: false
    sidebar_search_disable: false
    feedback:
      enable: false
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
    readingtime:
      enable: false
  links:
    user:
     # - name: User mailing list
     #   url: 'https://example.org/mail'
     #   icon: fa fa-envelope
     #   desc: Discussion and help from your fellow users
      - name: Facebook
        url: 'https://www.facebook.com/CrestfallenOwner/'
        icon: fab fa-facebook
      - name: Discord
        url: 'https://www.crestfallenlarp.com/discord'
        icon: fab fa-discord
      - name: Youtube
        url: 'https://www.youtube.com/@crestfallenlarp618'
        icon: fab fa-youtube
      - name: Email the Staff
        url: 'mailto:CrestfallenLARP@gmail.com'
        icon: fa fa-envelope
      # - name: Join the Mailing List
      #  url: 'https://buttondown.email/CrestfallenLARP'
      #  icon: fa fa-envelope


permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

languages:
  en:
    title: Crestfallen
    description: Crestfallen
    languageName: English
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  page:
    - HTML
    - print
    - RSS

outputFormats:
  Calendar:
    protocol: http://
module:
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
menu:
  main:
    - name: Schedule
      pre: <i class="fa-solid fa-calendar"></i>
      weight: 10
      url: '/schedule'
    - name: Rules
      pre: <i class="fa-regular fa-book"></i>
      weight: 30
      url: '/rules'
    - name: Blog
      pre: <i class="fa-solid fa-bullhorn"></i>
      weight: 40
      url: '/blog'
    - name: Katalossa 
      pre: <i class="fa-solid fa-earth-oceania"></i>
      weight: 40
      url: '/katalossa'