baseURL: /
title: Crestfallen
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true
taxonomies:
  tag: tags
  category: categories
params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
  copyright: Beren Olean
  privacy_policy: 'https://policies.google.com/privacy'
  version_menu: Releases
  archived_version: false
  version: '0.0'
  # url_latest_version: 'https://example.com'
  # github_repo: 'https://github.com/sjbennett123/crestfallen'
  # github_project_repo: 'https://github.com/google/docsy'
  # github_branch: master
  # gcs_engine_id: d72aa9b2712488cc3
  algolia_docsearch: false
  offlineSearch: true
  prism_syntax_highlighting: false
  ui:
    breadcrumb_disable: false
    footer_about_disable: true
    navbar_logo: true
    navbar_translucent_over_cover_disable: true
    sidebar_menu_compact: false
    sidebar_search_disable: false
    feedback:
      enable: false
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
    readingtime:
      enable: false
  links:
    user:
     # - name: User mailing list
     #   url: 'https://example.org/mail'
     #   icon: fa fa-envelope
     #   desc: Discussion and help from your fellow users
      - name: Facebook
        url: 'https://www.facebook.com/CrestfallenOwner/'
        icon: fab fa-facebook
        desc: It's Facebook!
      - name: Discord
        url: 'https://example.org/slack'
        icon: fab fa-discord
        desc: Chat with other project developers

permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: UA-00000000-0
languages:
  en:
    title: Crestfallen
    description: Crestfallen
    languageName: English
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    - print
    - RSS
module:
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
menu:
  main:
    - name: 
      pre: <i class="fab fa-facebook-f"></i>
      weight: 80
      url: 'https://www.facebook.com/groups/5471128642983855'
    - name: Events
      pre: <i class="fa-solid fa-calendar"></i>
      weight: 10
      url: '/rules'
    - name: Camps
      pre: <i class="fa-solid fa-tents"></i>
      weight: 20
      url: '/rules'
    - name: Rules
      pre: <i class="fa-regular fa-book"></i>
      weight: 30
      url: '/rules'
    - name: Blog
      pre: <i class="fa-solid fa-bullhorn"></i>
      weight: 40
      url: '/blog'
    - name: About
      weight: 90
      url: '/about'