baseURL: https://cfldangerden.netlify.app/
title: Crestfallen DANGER DEN
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true
ui.sidebar_menu_compact: true
ui.sidebar_menu_foldable:  true
params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
  copyright: Beren Olean
  version_menu: Releases
  archived_version: false
  version: '0.0'
  # url_latest_version: 'https://example.com'
  # github_repo: 'https://github.com/sjbennett123/crestfallen'
  # github_project_repo: 'https://github.com/google/docsy'
  # github_branch: master
  # gcs_engine_id: d72aa9b2712488cc3
  offlineSearch: true
  prism_syntax_highlighting: false
  ui:
    breadcrumb_disable: false
    footer_about_enable: false
    navbar_logo: true
    navbar_translucent_over_cover_disable: false
    sidebar_menu_compact: false
    sidebar_search_disable: false
    feedback:
      enable: false
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we
        can improve</a>.
    readingtime:
      enable: false
  links:
    user:
     # - name: User mailing list
     #   url: 'https://example.org/mail'
     #   icon: fa fa-envelope
     #   desc: Discussion and help from your fellow users
      - name: Facebook
        url: 'https://www.facebook.com/CrestfallenOwner/'
        icon: fab fa-facebook
      - name: Discord
        url: 'https://www.crestfallenlarp.com/discord'
        icon: fab fa-discord
      - name: Youtube
        url: 'https://www.youtube.com/@crestfallenlarp618'
        icon: fab fa-youtube
      - name: Email the Staff
        url: 'mailto:CrestfallenLARP@gmail.com'
        icon: fa fa-envelope
      # - name: Join the Mailing List
      #  url: 'https://buttondown.email/CrestfallenLARP'
      #  icon: fa fa-envelope


permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

languages:
  en:
    title: Crestfallen DANGER DEN
    languageName: English
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  page:
    - HTML
    - print
    - RSS

outputFormats:
  Calendar:
    protocol: https://
module:
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
menu:
  main:
    - name: Sample
      pre: <i class="fa-solid fa-book"></i>
      weight: 9
      url: '/sample_event_overview'
    - name: Overview
      pre: <i class="fa-solid fa-book"></i>
      weight: 10
      url: '/event_overview'
    - name: Guide 
      pre: <i class="fa-regular fa-scroll"></i>
      weight: 11
      url: '/guide'
    - name: Factions 
      pre: <i class="fa-regular fa-scroll"></i>
      weight: 30
      url: '/factions'
    - name: Characters 
      pre: <i class="fa-solid fa-users"></i>
      weight: 40
      url: '/characters'
    - name: Tags 
      pre: <i class="fa-solid fa-tags"></i>
      weight: 50
      url: '/tags'
    - name: Equipment  
      pre: <i class="fa-solid fa-wrench"></i>
      weight: 60
      url: '/equipment'
